
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!DOCTYPE html>
<html>
<head>

    <title>Chess</title>

    <style>
        body  { text-align       : center          ; }
        table { margin-left      : auto            ;
            margin-right     : auto            ;
            border           : 2px solid Black ;
            border-collapse  : collapse        ;
            color            : Beige           ;
            background-color : Sienna          ;
            text-align       : center          ;
            font-family      : Tahoma          ;
            font-weight      : bold            ; }
        td    { width            : 50px            ;
            height           : 50px            ; }
        input { text-align       : center          ; }
        .light { background-color : Beige           ; color: black; }
        .dark  { background-color : BurlyWood       ; color: black; }
        .info1 { position         : fixed           ;
            top              : 20px            ;
            left             : 10px            ; }
        .info2 { position         : fixed           ;
            top              : 40px            ;
            left             : 10px            ;
            text-align       : left            ; }
        button {
            padding: 0;
            border: none;
            background: none;
            font-size: 30px}
    </style>

    <script>
        var numberlabel='8'; //variable for indicating digit index of board cell
        var letterlabel = "A"; //variable for indicating digit index of board cell
        //---------------------------------------------------------------------------------------------------------------------------
        var turn        = "White"  ;
        var squareClass = "light"  ;
        //---------------------------------------------------------------------------------------------------------------------------
        function toggleTurn        ()  { if ( turn        == "White" ) { turn        = "Black" ; } else { turn        = "White" ; } }
        function toggleSquareClass ()  { if ( squareClass == "light" ) { squareClass = "dark"  ; } else { squareClass = "light" ; } }
        function getNextCharacter     ( character )  { return String.fromCodePoint( character.codePointAt(0) + 1 ) ; }
        function getPreviousCharacter ( character )  { return String.fromCodePoint( character.codePointAt(0) - 1 ) ; }
        //---------------------------------------------------------------------------------------------------------------------------
    </script>

</head>
<body>

<br>
<table>
    <tr>
        <td> </td>
        <td>A</td>
        <td>B</td>
        <td>C</td>
        <td>D</td>
        <td>E</td>
        <td>F</td>
        <td>G</td>
        <td>H</td>
        <td> </td>
    </tr>

    <script>
        for (var row = 1;row <= 8;row++) //loop which goes from very first row of board to the last not including rows with letters
        {
            document.write("<tr>"); //starting row tag
            letterlabel = "A"; //this variable is responsible to be set for "A" value as every row our inner loop will go from "A" to "H"
            for (var column = 1;column <= 10;column++) //inner loop for going through all columns in a row
            {
                if (column == 1 || column == 10) //checking if it is column for displaying number label of a row
                {
                    document.write("<td>" + numberlabel + "</td>"); //setting cell with number label
                }
                else
                {
                    document.write("<td class=" + squareClass + "><button id=\"" + letterlabel + numberlabel + "\"></button></td>"); //setting cell with id corresponding for current cell position, generated by letterlabel and numberlabel
                    if (row == 2) //checking if it is row for black pawns
                    {
                        document.getElementById(letterlabel + numberlabel).innerHTML = "♟"; //setting black pawn images for cell ID generated by letterlable and numberlabel of current cell
                    }
                    else if (row == 7) //checking if it is row for white pawns
                    {
                        document.getElementById(letterlabel + numberlabel).innerHTML = "♙"; //setting white pawn images for cell ID generated by letterlable and numberlabel of current cell
                    }
                    toggleSquareClass(); //changing style (background) of cell for the next one
                    letterlabel = getNextCharacter(letterlabel); //replacing current letter label for the next one in alphabet
                }
            }
            numberlabel=getPreviousCharacter(numberlabel); //replacing current digit label for the next one
            document.write("</tr>"); //closing row tag
            toggleSquareClass(); //changing style (background) of cell for the next one, so board will get needed pattern
        }
        //code for setting other figures using IDs we just set up
        document.getElementById("A1").innerHTML = "♖";
        document.getElementById("B1").innerHTML = "♘";
        document.getElementById("C1").innerHTML = "♗";
        document.getElementById("D1").innerHTML = "♕";
        document.getElementById("E1").innerHTML = "♔";
        document.getElementById("F1").innerHTML = "♗";
        document.getElementById("G1").innerHTML = "♘";
        document.getElementById("H1").innerHTML = "♖";
        document.getElementById("A8").innerHTML = "♜";
        document.getElementById("B8").innerHTML = "♞";
        document.getElementById("C8").innerHTML = "♝";
        document.getElementById("D8").innerHTML = "♛";
        document.getElementById("E8").innerHTML = "♚";
        document.getElementById("F8").innerHTML = "♝";
        document.getElementById("G8").innerHTML = "♞";
        document.getElementById("H8").innerHTML = "♜";
    </script>

    <tr>
        <td> </td>
        <td>A</td>
        <td>B</td>
        <td>C</td>
        <td>D</td>
        <td>E</td>
        <td>F</td>
        <td>G</td>
        <td>H</td>
        <td> </td>
    </tr>
</table>

</body>
</html>